# Generated by Django 5.1.7 on 2025-04-13 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='hive',
        ),
        migrations.CreateModel(
            name='Beehive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beehives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeehiveMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('Weight', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beehive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='sensors.beehive')),
            ],
        ),
        migrations.DeleteModel(
            name='Hive',
        ),
        migrations.DeleteModel(
            name='SensorReading',
        ),
    ]
