# Generated by Django 5.1.7 on 2025-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_remove_sensorreading_hive_beehive_beehivemetrics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beehive',
            name='user',
        ),
        migrations.AlterField(
            model_name='beehive',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='beehive',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
