# Generated by Django 5.1.7 on 2025-04-13 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_remove_beehive_user_alter_beehive_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beehive',
            name='Humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='beehive',
            name='Temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='beehive',
            name='Weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='beehive',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beehive',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beehive',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beehivemetrics',
            name='beehive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.beehive'),
        ),
    ]
