# Generated by Django 5.1.7 on 2025-04-14 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_beehive_humidity_beehive_temperature_beehive_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beehive',
            name='Humidity',
        ),
        migrations.RemoveField(
            model_name='beehive',
            name='Temperature',
        ),
        migrations.RemoveField(
            model_name='beehive',
            name='Weight',
        ),
        migrations.AddField(
            model_name='beehivemetrics',
            name='Battery_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='beehivemetrics',
            name='CO2',
            field=models.FloatField(default=4),
        ),
        migrations.AlterField(
            model_name='beehive',
            name='location',
            field=models.CharField(default='Default Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='beehive',
            name='name',
            field=models.CharField(default='samanta', max_length=255),
        ),
        migrations.AlterField(
            model_name='beehive',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beehives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beehivemetrics',
            name='Humidity',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='beehivemetrics',
            name='Temperature',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='beehivemetrics',
            name='Weight',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='beehivemetrics',
            name='beehive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='sensors.beehive'),
        ),
    ]
