# Generated by Django 5.1.7 on 2025-04-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_remove_beehive_humidity_remove_beehive_temperature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beehivemetrics',
            old_name='CO2',
            new_name='ExternalTemperature',
        ),
        migrations.RemoveField(
            model_name='beehivemetrics',
            name='Battery_level',
        ),
    ]
