# Generated by Django 5.1.7 on 2025-05-03 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beehive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('CO2', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature', models.CharField(blank=True, max_length=255, null=True)),
                ('humidity', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('battery_level', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeehiveMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CO2', models.CharField(max_length=255)),
                ('temperature', models.CharField(max_length=255)),
                ('humidity', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('battery_level', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beehive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='beehive.beehive')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
