# Generated by Django 5.1.7 on 2025-05-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beehive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beehive',
            old_name='CO2',
            new_name='external_temperature',
        ),
        migrations.RenameField(
            model_name='beehivemetrics',
            old_name='CO2',
            new_name='external_temperature',
        ),
    ]
