# Generated by Django 5.1.7 on 2025-06-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beehive', '0002_rename_co2_beehive_external_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beehivemetrics',
            name='battery_level',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='beehivemetrics',
            name='external_temperature',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='beehivemetrics',
            name='humidity',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='beehivemetrics',
            name='temperature',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='beehivemetrics',
            name='weight',
            field=models.FloatField(max_length=255),
        ),
    ]
