# Generated by Django 5.1.7 on 2025-04-13 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('TEMP', 'Temperature'), ('HUMIDITY', 'Humidity'), ('WEIGHT', 'Weight'), ('ACTIVITY', 'Activity'), ('OTHER', 'Other')], max_length=10)),
                ('alert_severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hive')),
            ],
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('prediction', models.TextField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hive_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hive')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature_inside', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_outside', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity_inside', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hive_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hive')),
            ],
        ),
    ]
