# Generated by Django 5.1.7 on 2025-05-03 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beehive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BeehiveMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CO2', models.FloatField()),
                ('Temperature', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('Weight', models.FloatField()),
                ('Battery_level', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beehive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='beehive_metrics.beehive')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
